
.build_template: &distro_build
  script:
    - meson -Dmanpage=false _build
    - ninja -C build install

stages:
  - build-os

fedora:stable:
  image: fedora:27
  stage: build-os
  before_script:
    - dnf update -y
    - >
      dnf install -y \
        gcc \
        meson \
        vala \
        gettext \
        glib2-devel \
        gtk3-devel \
        libgee-devel \
        folks-devel \
        evolution-data-server-devel \
        gnome-desktop3-devel \
        cheese-libs-devel \
        gnome-online-accounts-devel \
        telepathy-glib-devel
  <<: *distro_build
  only:
    - schedules
    - web
    - tags
