include: 'https://gitlab.gnome.org/GNOME/citemplates/raw/master/flatpak/flatpak_ci_initiative.yml'

stages:
- test
- deploy

variables:
  BUNDLE: 'gnome-contacts.flatpak'

flatpak:
  image: registry.gitlab.gnome.org/gnome/gnome-runtime-images/gnome:master
  variables:
    MANIFEST_PATH: 'data/flatpak/org.gnome.Contacts.Devel.json'
    MESON_ARGS: "-Dprofile=development"
    FLATPAK_MODULE: "gnome-contacts"
    RUNTIME_REPO: "https://nightly.gnome.org/gnome-nightly.flatpakrepo"
    APP_ID: "org.gnome.Contacts.Devel"
  extends: .flatpak

nightly:
  extends: '.publish_nightly'
  dependencies:
    - 'flatpak'
